import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "./providers";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/*导航*/}
        <nav>
          <div style={{ display: "flex", gap: "10px" }}>
            <Link href={"/about"}>About</Link>
            <Link href={"/blog"}>Blog</Link>
          </div>
        </nav>

        {/*页面*/}
        <Providers>{children}</Providers>

        {/*页脚*/}
        <footer>
          <p>@2024 这个是我的学习笔记</p>
        </footer>
      </body>
    </html>
  );
}
